@startuml DomainModelDiagram

package "Inventory <<Bounded Context>>" #DDDDDD {

    class Inventory <<Entity>> <<Aggregate Root>> {
        -ID : long
        -Description : string
    }
      
}

package "POS <<Bounded Context>>" #DDDDDD {

    class POS <<Entity>> {
        -ID : long
        -Description : string
        -location : string
    }
}

package "User <<Bounded Context>>" #DDDDDD {
    
    class User <<Entity>>{
        -ID : long
        -Description : string
    }
}

Inventory "U" .. "D" POS : Customer Supplier

package "MealItem <<Bounded Context>>" #DDDDDD {

    class MealItem <<Entity>> <<Aggregate Root>> {
        -ID : long
        -ProductionDate : datetime
        -ExpirationDate : datetime
        -MealIdentificationNumberStatic : string
        -MealID : long
    }

    object InventoryID <<Value Object>>

    object MealID <<Value Object>>

    MealItem -- InventoryID
    MealItem -- MealID
    Inventory "D" -- "U" MealItem : Customer Supplier
}

package "Meal <<Bounded Context>>" #DDDDDD {

    class Meal <<Entity>> <<Aggregate Root>> {
        -ID : long
        -Description : string
        -AlergicComponents : List<AlergicComponent>
        -Ingredients : List<Ingredient>
        -MealDescriptors : List<MealDescriptor>

        +void AddAlergicComponent()
        +void AddIngredient()
        +void AddMealDescriptor()

        +void RemoveAlergicComponent()
        +void RemoveIngredient()
        +void RemoveMealDescriptor()
    }

    class Ingredient <<Entity>> {
        -ID : long
        -Description : string
    }

    class AlergicComponent <<Entity>> {
        -ID : long
        -Description : string
    }

    class MealDescriptor <<Entity>> {
        -ID : long
        -Description : string
        -Name : string
    }

    object MealIdentificationNumber <<ValueObject>> {
        -MealIdentificationNumberPrefix : string

        +bool ChangeMealIdentificationNumberGen()
        +string GenerateMealIdentificationNumber()
    }

    object Meal.MealID <<Value Object>>

    Meal "0..*" -- "0..*" AlergicComponent
    Meal "1" -- "0..*" MealDescriptor
    Meal "0..*" -- "1..*" Ingredient
    Meal "1" -- "1" MealIdentificationNumber
    Meal "1" -- "1" Meal.MealID
}

Meal "U" .. "D" MealItem : Customer Supplier


package "Log <<Bounded Context>>" #DDDDDD {

    interface WriteLog

    class EventLog  {
        -ID : long
        -Description : string
        -UserTypeID : User
        -Action : EventAction
        -Class : T
        -Date : DateTime

        +WriteLog()
    }

    enum EventAction {
        - Add
        - Create
        - Update
        - Delete
    }

    class UserType {
        -ID : long
        -Description : string
    }

    object UserTypeID <<ValueObject>>

    WriteLog <|.. EventLog
    EventLog -- UserTypeID
    EventLog -- EventAction
    EventLog -- UserType
    EventLog "U" -- "D" User : Conformist
}


@enduml
