@startuml DeploymentDiagram
left to right direction

node ClientPC {
    component GorgeousMealUI
}

node AppServer {
    component GorgeousMealAPI
}

node SchoolUserDatabaseServer {
    database UserDB
}

node SchoolDatabaseServer {
    database MealDB
}

GorgeousMealUI -(0- GorgeousMealAPI : HTTPS
GorgeousMealAPI -- UserDB : TCP
GorgeousMealAPI -- MealDB : TCP
@enduml