@startuml DomainModelDiagram
class Meal {
    -ID : long
    -Description : string
    -MealIdentificationNumber : string
    -AlergicComponent : List<AlergicComponent>
    -Ingredient : List<Ingredient>
    -MealDescriptor : List<MealDescriptor>
    
    +bool ChangeMealIdentificationNumberGen()

    +void AddAlergicComponent()
    +void AddIngredient()
    +void AddMealDescriptor()

    +void RemoveAlergicComponent()
    +void RemoveIngredient()
    +void RemoveMealDescriptor()
}

class MealItem {
    -ID : long
    -Description : string
    -ProductionDate : datetime
    -ExpirationDate : datetime
    -Meal : Meal
}

class Ingredient {
    -ID : long
    -Description : string
}

class AlergicComponent {
    -ID : long
    -Description : string
}

class MealDescriptor {
    -ID : long
    -Description : string
    -Name : string
}

class Sale {
    -ID : long
    -DateSold : datetime
    -Checkout : bool
    -PaymentValue : double
    -MealItems : List<MealItem>

    +void AddSoldMealItem()
    +void RemoveSoldMealItem()
    +bool Checkout()
}

Meal "0..*" -- "0..*" AlergicComponent
Meal "1" -- "0..*" MealDescriptor
Meal "0..*" -- "1..*" Ingredient

MealItem "0..*" -- "1" Meal

Sale "0..1" -- "1..*" MealItem
@enduml