@startuml APILayersDiagram
left to right direction

package "GorgeousFoodAPI"{
    [Controller] -up- API_Endpoint
    [Service] -- ServiceData
    [Entity] -up- EntityData
    [Repository] -left- RepoData

    Service --(RepoData
    Controller --(ServiceData
    Service --(EntityData
    Entity --(RepoData

    Repository --UserDB :TCP
    Repository --MealDB :TCP
}

package "ClientPC"{
    [GorgeousFoodUI] --( API_Endpoint
}

package "DBServer"{
    database "UserDB"{
    }
}
package "DBServer2"{
    database "MealDB"{
    }
}

@enduml
