@startuml DeploymentDiagram
left to right direction

node Docker{
    node AppService1Container {
        component GorgeousMealUI
    }

    node AppService2Container {
        component GorgeousMealAPI
    }

    node DatabaseContainer {
        database MealDB
    }

    node SchoolUserDatabaseContainer {
        database UserDB
    }
}

GorgeousMealUI -(0- GorgeousMealAPI : HTTPS
GorgeousMealAPI -- UserDB : TCP
GorgeousMealAPI -- MealDB : TCP

@enduml